version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

volumes:
  dbdata:
